[package]
name = "stanza"
version = "0.1.0"
edition = "2021"
readme = "../README.md"
authors = ["Emil Koutanov"]
license = "MIT"
description = "An abstract table model with customisable text formatting and renderers."
repository = "https://github.com/obsidiandynamics/stanza"
keywords = ["cli", "terminal", "table", "format", "no_std"]

[dependencies]

[dev-dependencies]
term_size = "0.3.2"
